version: '3.5'

services:
  # database:
  #   image: fosol:database
  #   profiles:
  #     - all
  #   restart: "no"
  #   container_name: fss-database
  #   build:
  #     context: db
  #   env_file:
  #     - db/.env
  #   ports:
  #     - ${DB_PORT:-30000}:1433
  #   volumes:
  #     - fosol-database:/var/opt/mssql
  #   networks:
  #     - fosol
      
  # api:
  #   image: fosol:api
  #   profiles:
  #     - all
  #   restart: "no"
  #   container_name: fss-api
  #   build:
  #     context: backend
  #     dockerfile: api/Dockerfile
  #   env_file:
  #     - backend/api/.env
  #   ports:
  #     - ${API_HTTP_PORT:-30001}:8080
  #     - ${API_HTTPS_PORT:-30002}:8443
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   networks:
  #     - fosol

  app:
    image: fosol:site
    profiles:
      - all
    stdin_open: true
    tty: true
    restart: "no"
    container_name: fss-site
    build:
      context: app
      dockerfile: Dockerfile
    env_file: ./app/.env
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
    ports:
      - ${APP_HTTP_PORT:-30003}:5173
      - ${APP_HTTPS_PORT:-30004}:5443
    extra_hosts:
      - host.docker.internal:host-gateway
    # depends_on:
    #   - api
    networks:
      - fosol

  nginx:
    image: fosol:nginx
    profiles:
      - all
    restart: "no"
    container_name: fss-nginx
    build:
      context: ./nginx
    env_file:
      - nginx/.env
    ports:
      - ${NGINX_HTTP_PORT:-30080}:80
      - ${NGINX_HTTPS_PORT:-30443}:443
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      # - api
      - app
    networks:
      - fosol

networks:
  fosol:
    name: fss-net
    driver: bridge

volumes:
  fosol-database:
    name: fss-database
