env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - standard-with-typescript
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: __dirname
plugins:
  - react
  - typescript-eslint
  - simple-import-sort
rules:
  {
    "react/react-in-jsx-scope": "off",
    "semi": [2, "never"],
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
  }
